networks:
  proxy-net:
    external: true
services: 
  app:
    container_name: app
    build: .
    restart: always #change if you don't want your container restarting
    networks:
      - proxy-net:
    environment:
      - NODE_ENV=production
